#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 0

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom --config $HOME/.config/picom/picom.conf &

$HOME/.config/polybar/launch.sh &

feh --bg-fill /home/mikey/walls/digital/a_car_driving_on_a_road_at_night.png /home/mikey/walls/digital/a_car_in_a_field_with_trees_and_a_fire.png
